ignored:
  - DL3015 
  - DL3020 
  - DL3018 

ignored-files:
  - "**/vendor/**"
  - "**/node_modules/**" 
  - "gestsup/vendor/**"
  - "*/vendor/*"

trusted-registries:
  - docker.io
  - ghcr.io

strict-labels: false
disable-ignore-pragma: false