version: '3.8'

services:
  # Base de données MySQL pour le développement
  mysql:
    image: mysql:8.0
    container_name: cesizen-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password
      MYSQL_DATABASE: cesizen_dev
      MYSQL_USER: cesizen_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - cesizen-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Laravel
  backend:
    image: ghcr.io/maodehka/cesizen-backend:develop
    container_name: cesizen-dev-backend
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:${LARAVEL_APP_KEY}
      APP_URL: http://cesizen-dev.chickenkiller.com
      
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: cesizen_dev
      DB_USERNAME: cesizen_user
      DB_PASSWORD: dev_password
      
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      MAIL_MAILER: log
      
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - backend_storage:/var/www/html/storage
      - backend_logs:/var/www/html/storage/logs
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cesizen-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Vue.js
  frontend:
    image: ghcr.io/maodehka/cesizen-frontend:develop
    container_name: cesizen-dev-frontend
    environment:
      VITE_API_URL: http://cesizen-dev.chickenkiller.com:8000/api
      VITE_APP_ENV: development
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cesizen-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis pour le cache et les sessions
  redis:
    image: redis:7-alpine
    container_name: cesizen-dev-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - cesizen-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx comme reverse proxy
  nginx:
    image: nginx:alpine
    container_name: cesizen-dev-nginx
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - cesizen-dev-network
    restart: unless-stopped

  # MailHog pour tester les emails en développement
  mailhog:
    image: mailhog/mailhog:latest
    container_name: cesizen-dev-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface web
    networks:
      - cesizen-dev-network
    restart: unless-stopped

  # Watchtower pour les mises à jour automatiques en dev
  watchtower:
    image: containrrr/watchtower
    container_name: cesizen-dev-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 300  # 5 minutes
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_LABEL_ENABLE: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - cesizen-dev-network
    restart: unless-stopped

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  backend_storage:
    driver: local
  backend_logs:
    driver: local

networks:
  cesizen-dev-network:
    driver: bridge